import type { Product } from "./types";

// Catálogo idêntico à referência (12 produtos). As imagens do Unsplash foram
// baixadas para /public/images — o campo `img` aponta para os arquivos locais e
// é fácil de trocar pelas fotos reais da Floravie depois.
export const PRODUCTS: Product[] = [
  {
    id: "r1",
    cat: "buques",
    name: "Buquê 12 Rosas Rosé",
    price: 189.9,
    img: "/images/prod-rosas-rose.jpg",
    badge: "Mais vendido",
    rating: 4.9,
    reviews: 482,
    desc: "Doze rosas em tons de rosé, selecionadas na manhã da entrega e finalizadas com folhagens frescas, papel artesanal e laço de cetim. Acompanha cartão escrito à mão.",
    sizes: [
      { l: "Padrão · 12 rosas", d: 0 },
      { l: "Grande · 18 rosas", d: 60 },
      { l: "Deluxe · 24 rosas", d: 120 },
    ],
  },
  {
    id: "g1",
    cat: "buques",
    name: "Buquê de Girassóis Alegria",
    price: 159.9,
    img: "/images/prod-girassois.jpg",
    badge: null,
    rating: 4.9,
    reviews: 316,
    desc: "Girassóis vibrantes embrulhados em papel kraft com toque rústico. A escolha certa para levar luz e bom humor a qualquer dia.",
    sizes: [
      { l: "Padrão · 5 girassóis", d: 0 },
      { l: "Grande · 8 girassóis", d: 45 },
    ],
  },
  {
    id: "c1",
    cat: "buques",
    name: "Buquê Flores do Campo",
    price: 139.9,
    img: "/images/prod-flores-campo.jpg",
    badge: "Novo",
    rating: 4.3,
    reviews: 97,
    desc: "Mistura despretensiosa de flores da estação em cores variadas, com aquele charme de colheita recém-feita.",
    sizes: [
      { l: "Padrão", d: 0 },
      { l: "Grande", d: 40 },
    ],
  },
  {
    id: "t1",
    cat: "buques",
    name: "Buquê Jardim Tropical",
    price: 174.9,
    img: "/images/prod-jardim-tropical.jpg",
    badge: null,
    rating: 4.9,
    reviews: 204,
    desc: "Cores intensas e texturas marcantes inspiradas nos jardins do Nordeste. Um presente impossível de passar despercebido.",
    sizes: [
      { l: "Padrão", d: 0 },
      { l: "Grande", d: 55 },
    ],
  },
  {
    id: "b1",
    cat: "buques",
    name: "Buquê Serenidade Branca",
    price: 199.9,
    img: "/images/prod-serenidade-branca.jpg",
    badge: null,
    rating: 4.9,
    reviews: 158,
    desc: "Flores brancas e rosadas em composição delicada, perfeitas para agradecer, acolher ou celebrar recomeços.",
    sizes: [
      { l: "Padrão", d: 0 },
      { l: "Grande", d: 50 },
    ],
  },
  {
    id: "s1",
    cat: "buques",
    name: "Buquê Surpresa da Florista",
    price: 149.9,
    img: "/images/prod-surpresa-florista.jpg",
    badge: null,
    rating: 4.9,
    reviews: 341,
    desc: "Deixe a criação por nossa conta: a florista monta um buquê exclusivo com as flores mais bonitas do dia. Sempre uma surpresa, sempre lindo.",
    sizes: [
      { l: "Padrão", d: 0 },
      { l: "Grande", d: 45 },
      { l: "Deluxe", d: 95 },
    ],
  },
  {
    id: "o1",
    cat: "vasos",
    name: "Orquídea Phalaenopsis Lilás",
    price: 219.9,
    img: "/images/prod-orquidea-lilas.jpg",
    badge: "Dura +30 dias",
    rating: 4.9,
    reviews: 721,
    desc: "Orquídea Phalaenopsis em vaso de vidro, com hastes floridas que duram semanas. Acompanha guia de cuidados.",
    sizes: [
      { l: "1 haste", d: 0 },
      { l: "2 hastes", d: 70 },
    ],
  },
  {
    id: "a1",
    cat: "arranjos",
    name: "Arranjo Jardim Rosé",
    price: 249.9,
    img: "/images/prod-arranjo-jardim-rose.jpg",
    badge: null,
    rating: 4.9,
    reviews: 263,
    desc: "Arranjo de mesa em tons de rosa montado em vaso de vidro, pronto para decorar sem precisar de nada além de água fresca.",
    sizes: [{ l: "Único", d: 0 }],
  },
  {
    id: "cf1",
    cat: "cestas",
    name: "Cesta Bom Dia com Flores",
    price: 289.9,
    img: "/images/prod-cesta-bom-dia.jpg",
    badge: "Café da manhã",
    rating: 4.9,
    reviews: 389,
    desc: "Café da manhã completo: pães, frutas, suco, geleia e bolo caseiro, decorado com flores frescas do ateliê.",
    sizes: [
      { l: "Para 1 pessoa", d: 0 },
      { l: "Para 2 pessoas", d: 80 },
    ],
  },
  {
    id: "v1",
    cat: "cestas",
    name: "Cesta Vinho & Delícias",
    price: 329.9,
    img: "/images/prod-cesta-vinho.jpg",
    badge: null,
    rating: 4.3,
    reviews: 142,
    desc: "Vinho tinto selecionado acompanhado de pães artesanais, queijos e antepastos. Para brindar bons momentos.",
    sizes: [{ l: "Única", d: 0 }],
  },
  {
    id: "u1",
    cat: "cestas",
    name: "Urso de Pelúcia com Laço",
    price: 99.9,
    img: "/images/prod-urso-pelucia.jpg",
    badge: "Fofura",
    rating: 4.9,
    reviews: 518,
    desc: "Urso de pelúcia macio com laço, o companheiro perfeito para acompanhar flores ou presentear sozinho.",
    sizes: [
      { l: "Médio · 30cm", d: 0 },
      { l: "Grande · 50cm", d: 60 },
    ],
  },
  {
    id: "cv1",
    cat: "cestas",
    name: "Cesta de Flores no Vime",
    price: 209.9,
    img: "/images/prod-cesta-vime.jpg",
    badge: null,
    rating: 4.9,
    reviews: 176,
    desc: "Flores frescas arranjadas em cesta de vime, uma peça que vira decoração assim que chega.",
    sizes: [
      { l: "Padrão", d: 0 },
      { l: "Grande", d: 45 },
    ],
  },
];

export const productById = (id: string): Product | undefined =>
  PRODUCTS.find((p) => p.id === id);
